categories: [Tool Dependency Packages,Metabolomics]
description: '[W4M][LC-MS] Script used by the suite_xcms'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org Thoses
  scripts are used by the [W4M][LC-MS] suite_xcms'
name: package_xcms_w4m_script_2_2_0
owner: lecorguille
