categories: [Metabolomics, Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and compiles the
  R bioconductor package xcms version 1.44.0
homepage_url: http://workflow4metabolomics.org
name: package_bioconductor_xcms_1_44_0
owner: lecorguille
