# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

env:
  - TESTFOLDER=.

before_install:
  - export GALAXY_RELEASE=release_19.05

install:
 - sudo apt-get install -y python-virtualenv
 - sudo pip install planemo==0.58.1
  
script:
 - planemo lint ${TRAVIS_BUILD_DIR}/${TESTFOLDER}
 - planemo test --galaxy_branch $GALAXY_RELEASE  --galaxy_source "$GALAXY_REPO" --no_cache_galaxy ${TRAVIS_BUILD_DIR}/${TESTFOLDER}

