categories:
  - Metabolomics
description: '[W4M][LC-MS] IPO'
homepage_url: https://github.com/rietho/IPO
long_description: 'Part of the W4M project: http://workflow4metabolomics.org'
name: ipo
owner: lecorguille
remote_repository_url: https://github.com/rietho/IPO