categories: 
  - Metabolomics
description: PhysioFit is a scientific tool designed to quantify cell growth parameters and uptake & production fluxes
name: physiofit
owner: workflow4metabolomics
remote_repository_url: https://github.com/MetaSys-LISBP/PhysioFit
