categories:
- Metabolomics
description: 'genform: generation of molecular formulas by high-resolution MS and MS/MS data'
homepage_url: https://sourceforge.net/projects/genform/
long_description: 'genform generates candidate molecular formulas from high-resolution 
MS data. It calculates match values (MV) that show how well candidate molecular formulas fit the MS 
isotope peak distributions (MS MV) and the high-resolution MS/MS fragment peak masses (MS/MS 
MV). Finally it computes a combined match value from these two scores.'
name: genform
owner: workflow4metabolomics
remote_repository_url: https://github.com/workflow4metabolomics/tools-metabolomics/blob/master/tools/genform/
