categories: [Metabolomics]
description: '[Metabolomics][W4M][NMR] NMR Annotation2D - Automatic annotation of bi-dimensional NMR spectra'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org'
name: 2dnmrannotation
owner: marie-tremblay-metatoul
remote_repository_url: https://github.com/workflow4metabolomics/tools-metabolomics
