categories: [Metabolomics]
description: '[W4M][LC-MS] XCMS R Package - Preprocessing - Integrate areas of missing
  peaks'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html For each sample,
  identify peak groups where that sample is not represented. For each of those peak
  groups, integrate the signal in the region of that peak group and create a new peak. BEWARE:
  this tool don''t come with its script. You will need to install the dedicated package_xcms_w4m_script
  too'
name: xcms_fillpeaks
owner: lecorguille
