categories: [Metabolomics]
description: '[W4M][LC-MS] XCMS R Package - Preprocessing - peaks calling in NetCDF/mzXML
  files'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html Filtration and
  Peak Identification using xcmsSet function from xcms R package to preprocess LC/MS
  data for relative quantification and statistical analysis BEWARE: this tool don''t
  come with its script. You will need to install the dedicated package_xcms_w4m_script
  too'
name: xcms_xcmsset
owner: lecorguille
